# Generated by Django 4.2.8 on 2023-12-19 05:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergen',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Mleko'), ('J', 'Jajka'), ('O', 'Orzechy'), ('S', 'Soja'), ('P', 'Pszenica'), ('Sk', 'Skorupiaki')], max_length=6, null=True),
        ),
    ]
