# Generated by Django 4.2.8 on 2023-12-19 05:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_allergen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergen',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('N', 'Nabiał'), ('J', 'Jajka'), ('O', 'Orzechy'), ('S', 'Soja'), ('G', 'Gluten'), ('Sk', 'Skorupiaki')], max_length=6, null=True),
        ),
    ]
